kind: pipeline
name: default

steps:
  - name: build image and push
    image: plugins/docker
    settings:
      repo: tbcloud/kubernite
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - tag